services:
  user-service:
    image: ghcr.io/deineskai/didge/didge-user-service:${IMAGE_TAG}
    ports:
      - "127.0.0.1:${USER_SERVICE_PORT}:8000"
    restart: always
    environment:
      - DATABASE_URL=sqlite:////data/users.db
    volumes:
      - ./db:/data

  household-service:
    image: ghcr.io/deineskai/didge/didge-household-service:${IMAGE_TAG}
    ports:
      - "127.0.0.1:${HOUSEHOLD_SERVICE_PORT}:8000"
    restart: always
    environment:
      - DATABASE_URL=sqlite:////data/households.db
    volumes:
      - ./db:/data

  culinary-service:
    image: ghcr.io/deineskai/didge/didge-culinary-service:${IMAGE_TAG}
    ports:
      - "127.0.0.1:${CULINARY_SERVICE_PORT}:8000"
    restart: always
    environment:
      - DATABASE_URL=sqlite:////data/culinary.db
    volumes:
      - ./db:/data

  frontend:
    image: ghcr.io/deineskai/didge/didge-frontend:${IMAGE_TAG}
    ports:
      - "127.0.0.1:${FRONTEND_PORT}:80"
    restart: always
    # environment:
    #  - USER_API_URL=url
    #  - HOUSEHOLD_API_URL=url
