services:
  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    container_name: user-service
    ports:
      - "127.0.0.1:8001:8000"
    restart: always
    # environment:
    #  - DATABASE_URL=db_url

  household-service:
    build:
      context: ./household-service
      dockerfile: Dockerfile
    container_name: household-service
    ports:
      - "127.0.0.1:8002:8000"
    restart: always
    # environment:
    #  - DATABASE_URL=db_url

  frontend:
    build:
      context: ./didge-frontend
      dockerfile: Dockerfile
      args:
        - BUILD_ENV=production
    container_name: didge-frontend
    ports:
      - "8080:80"
    restart: always
