services:
  user-service:
    image: ghcr.io/deineskai/didge/user-service:latest
    container_name: didge-user-service
    ports:
      - "127.0.0.1:8001:8000"
    restart: always
    environment:
      - DATABASE_URL=sqlite:////data/users.db
    volumes:
      - ./db:/data

  household-service:
    image: ghcr.io/deineskai/didge/household-service:latest
    container_name: didge-household-service
    ports:
      - "127.0.0.1:8002:8000"
    restart: always
    environment:
      - DATABASE_URL=sqlite:////data/households.db
    volumes:
      - ./db:/data

  frontend:
    image: ghcr.io/deineskai/didge/frontend:latest
    container_name: didge-frontend
    ports:
      - "8080:80"
    restart: always
    # environment:
    #  - USER_API_URL=url
    #  - HOUSEHOLD_API_URL=url
